// Package layerc implements the FairPlay bridge's output encoding natively.
//
// EncodeX9 turns the final 9-block bridge digest into x9Data, the 64 bytes
// Phase 2 consumes, of which the first 20 are payload-dependent. Its input is
// 64 bytes: the 32 around the digest at flat 15712, followed by the last 32
// bytes of the GP buffer -- established by fault injection, and the only
// payload-dependent input the encoding reads.
//
// Verified bit-exact against the interpreter for 213 payloads, 200 of them
// random (TestLayerCNativeEncode in internal/m3trace). With this, the whole of
// Phase 1 is native: see docs/layer-a-delta-chaining.md.
//
// Generated by scratch/layera_emit.py. See internal/layera for what the 16KB
// constant memory image in each generated file is and why it holds no Apple
// address.
package layerc
