// Code generated by scratch/layera_compress.py; DO NOT EDIT.

package layerc

// The traced window is 32-bit ARM arithmetic over a 64-bit register file. Named
// here rather than spelled out at each of the ~200,000 sites that use them,
// which is both far smaller and closer to the instruction each one came from.
// All are trivially inlinable, so this costs nothing at runtime.

func add32(a, b uint64) uint64 { return uint64(uint32(a) + uint32(b)) }
func sub32(a, b uint64) uint64 { return uint64(uint32(a) - uint32(b)) }
func and32(a, b uint64) uint64 { return uint64(uint32(a) & uint32(b)) }
func orr32(a, b uint64) uint64 { return uint64(uint32(a) | uint32(b)) }
func eor32(a, b uint64) uint64 { return uint64(uint32(a) ^ uint32(b)) }
func mul32(a, b uint64) uint64 { return uint64(uint32(a) * uint32(b)) }

// bfi32 is BFI/BFXIL: replace the field of d selected by keep with the field of
// s selected by mask, shifted into place.
func bfi32(d, s, keep, mask, sh uint64) uint64 {
	return uint64((uint32(d) &^ uint32(keep)) | ((uint32(s) & uint32(mask)) << sh))
}

// ubfx32 is UBFX: extract the field at sh selected by mask.
func ubfx32(a, sh, mask uint64) uint64 { return uint64((uint32(a) >> sh) & uint32(mask)) }

func b2u(c bool) uint64 {
	if c {
		return 1
	}
	return 0
}

// cmp32 and cmp64 return the comparands alongside the flags because both stay
// live: the generated chunks hand fA and fB to each other across boundaries.
func cmp32(a, b uint64) (uint64, uint64, bool, bool, bool) {
	a, b = uint64(uint32(a)), uint64(uint32(b))
	return a, b, a == b, a >= b, (a-b)>>31&1 == 1
}

func cmp64(a, b uint64) (uint64, uint64, bool, bool, bool) {
	return a, b, a == b, a >= b, (a-b)>>63&1 == 1
}
