// SPDX-License-Identifier: BlueOak-1.0.0

package fairplayhash

// SPN#1's full MixColumns (all 4 columns) as a GF(2)-affine 128-bit map, plus
// the payload-independent constant round-0 input. Generated by
// TestExtractFullMix (EXTRACT_FULLMIX=1); held-out verified, chain-verified.
//
// MixColumns acts on each 32-bit column independently, so the 128x128 bit
// matrix is block diagonal and its four 32x32 blocks are identical. Only one
// block is stored -- 128 bytes rather than 2048 -- and the full matrix is
// rebuilt from it. Built as a variable initialiser, not in an init(), because
// spn1_mixcol_fast.go repacks this into words and Go runs every variable
// initialiser before any init().

const spn1MixBlock = "RS\x01\x01\x8a\x88\x02\x02.*\x04\x04\xed\xe5\b\b\x8e\x9e\x10\x10\xa6\x86  \x96\xd6@@w\xf7\x80\x80\x01RS\x01\x02\x8a\x88\x02\x04.*\x04\b\xed\xe5\b\x10\x8e\x9e\x10 \xa6\x86 @\x96\xd6@\x80w\xf7\x80\x01\x01RS\x02\x02\x8a\x88\x04\x04.*\b\b\xed\xe5\x10\x10\x8e\x9e  \xa6\x86@@\x96\xd6\x80\x80w\xf7S\x01\x01R\x88\x02\x02\x8a*\x04\x04.\xe5\b\b\xed\x9e\x10\x10\x8e\x86  \xa6\xd6@@\x96\xf7\x80\x80w"

var SPN1MixColRows = buildMixColRows()

func buildMixColRows() (rows [128][16]byte) {
	for r := 0; r < 128; r++ {
		col := r / 32
		for k := 0; k < 4; k++ {
			rows[r][col*4+k] = spn1MixBlock[(r%32)*4+k]
		}
	}
	return
}

var SPN1MixColConst = [16]byte{0x0c, 0x48, 0x79, 0x5f, 0x0c, 0x48, 0x79, 0x5f, 0x0c, 0x48, 0x79, 0x5f, 0x0c, 0x48, 0x79, 0x5f}

// SPN1CoreInput is SPN#1's payload-independent round-0 plaintext.
var SPN1CoreInput = [16]byte{0x0f, 0x54, 0x5e, 0x5a, 0xb7, 0x7e, 0x16, 0x80, 0x1a, 0xed, 0xd5, 0x81, 0xd0, 0x87, 0x26, 0xdc}
