// SPDX-License-Identifier: BlueOak-1.0.0

package fairplayhash

// SPN#1's trailing output-encoding stage is an AES FINAL round (SubBytes +
// ShiftRows + AddRoundKey, no MixColumns) folded into 16 byte->byte tables:
//
//	out[p] = SPN1TrailTables[p][ in[spn1TrailShiftRows[p]] ]
//
// Verified: each output byte is a pure function of a single input byte (fan-in
// 1), the source permutation is AES ShiftRows, and the 16 tables reproduce all
// 6000 captured (in,out) samples with full 256/256 coverage.
// Constants are generated by TestExtractTrailing (EXTRACT_TRAILING=1) and pinned
// by TestApplyTrailingMatchesSamples.

var spn1TrailShiftRows = [16]int{0, 5, 10, 15, 4, 9, 14, 3, 8, 13, 2, 7, 12, 1, 6, 11}

// ApplyTrailing computes SPN#1's final output from its round-8 output.
func ApplyTrailing(in [16]byte) [16]byte {
	var out [16]byte
	for p := 0; p < 16; p++ {
		out[p] = SPN1TrailTables[p][in[spn1TrailShiftRows[p]]]
	}
	return out
}
