// Package layera implements the FairPlay Layer-A inter-block chaining delta
// natively, in plain Go: no build tag, no memory snapshot, no ARM64 interpreter.
//
// DeltaB4 computes the delta shared by bridge blocks B4 and C3 from the first
// 47 bytes of the Phase-1 GP buffer. Its companion, DeltaB5 in
// internal/layerab5, computes the delta shared by B5 and C4 from gp[47:111].
// Together with delta(C1), which is a payload-independent constant, those are
// all of Layer A.
//
// The code is generated by scratch/layera_emit.py from an execution trace. The
// traced instruction stream is payload-independent, so the generated form needs
// no branches; addresses that were measured to be payload-independent are
// constant-folded, and the ~150 that are not are computed at runtime against
// baked tables. Correctness is not assumed from that construction: it is
// checked bit-exactly against the interpreter over hundreds of independently
// generated payloads by TestLayerANativeDeltaB4 and TestLayerANativeDeltaB4Random
// in internal/m3trace.
//
// See docs/layer-a-delta-chaining.md and docs/layer-a-researcher-handoff.md.
package layera
