// Package layerb implements the FairPlay bridge's per-block message
// construction natively, in plain Go.
//
// Each of the 9 bridge-hash blocks compresses a 64-byte message. Four of them
// (B1, B2, C1, C2) are payload-independent constants. The other five are
// functions of one contiguous slice of the Phase-1 GP buffer:
//
//	MsgB3  gp[0:47]      MsgC3  gp[0:47]
//	MsgB4  gp[47:111]    MsgC4  gp[47:111]
//	MsgB5  gp[111:128]
//
// The B and C blocks consume identical slices but are NOT the same function --
// message(B3) != message(C3) and message(B4) != message(C4) -- so all five are
// distinct derivations.
//
// Generated by scratch/layera_emit.py and verified bit-exact against the
// interpreter. See docs/layer-a-delta-chaining.md for how the generator works.
package layerb
